import SwiftUI
import Foundation

let customFlagImageURLByCode: [String: URL] = [
    "AB": URL(string: "https://commons.wikimedia.org/wiki/Special:FilePath/Flag_of_the_Republic_of_Abkhazia.svg?width=1280")!,
    "OS": URL(string: "https://commons.wikimedia.org/wiki/Special:FilePath/Flag_of_South_Ossetia.svg?width=1280")!,
    "NC": URL(string: "https://commons.wikimedia.org/wiki/Special:FilePath/Flag_of_the_Turkish_Republic_of_Northern_Cyprus.svg?width=1280")!,
    "SLD": URL(string: "https://commons.wikimedia.org/wiki/Special:FilePath/Flag_of_Somaliland.svg?width=1280")!
]

struct Country: Identifiable, Equatable, Codable {
    let code: String
    let name: String
    let continent: String

    var id: String { code }
    var flagImageURL: URL? {
        customFlagImageURLByCode[code] ?? URL(string: "https://flagcdn.com/w1280/\(code.lowercased()).png")
    }
}

let capitalByCountryCode: [String: String] = [
    "AF": "Kabul", "AL": "Tirana", "DZ": "Algier", "AD": "Andorra la Vella", "AO": "Luanda",
    "AG": "St. John's", "AR": "Buenos Aires", "AM": "Jerewan", "AZ": "Baku", "AU": "Canberra",
    "BS": "Nassau", "BH": "Manama", "BD": "Dhaka", "BB": "Bridgetown", "BE": "Brüssel",
    "BZ": "Belmopan", "BJ": "Porto-Novo", "BT": "Thimphu", "BO": "Sucre", "BA": "Sarajevo",
    "BW": "Gaborone", "BR": "Brasília", "BN": "Bandar Seri Begawan", "BG": "Sofia", "BF": "Ouagadougou",
    "BI": "Gitega", "CL": "Santiago de Chile", "CN": "Peking", "CR": "San José", "DE": "Berlin",
    "DM": "Roseau", "DO": "Santo Domingo", "DJ": "Dschibuti", "DK": "Kopenhagen", "EC": "Quito",
    "SV": "San Salvador", "CI": "Yamoussoukro", "ER": "Asmara", "EE": "Tallinn", "FJ": "Suva",
    "FI": "Helsinki", "FR": "Paris", "GA": "Libreville", "GM": "Banjul", "GE": "Tiflis",
    "GH": "Accra", "GD": "St. George's", "GR": "Athen", "GT": "Guatemala-Stadt", "GN": "Conakry",
    "GW": "Bissau", "GY": "Georgetown", "HT": "Port-au-Prince", "HN": "Tegucigalpa", "IN": "Neu-Delhi",
    "ID": "Jakarta", "IQ": "Bagdad", "IR": "Teheran", "IE": "Dublin", "IS": "Reykjavík",
    "IL": "Jerusalem", "IT": "Rom", "JM": "Kingston", "JP": "Tokio", "YE": "Sanaa",
    "JO": "Amman", "KH": "Phnom Penh", "CM": "Yaoundé", "CA": "Ottawa", "CV": "Praia",
    "KZ": "Astana", "QA": "Doha", "KE": "Nairobi", "KG": "Bischkek", "KI": "South Tarawa",
    "CO": "Bogotá", "KM": "Moroni", "CG": "Brazzaville", "CD": "Kinshasa", "HR": "Zagreb",
    "CU": "Havanna", "KW": "Kuwait-Stadt", "LA": "Vientiane", "LS": "Maseru", "LV": "Riga",
    "LB": "Beirut", "LR": "Monrovia", "LY": "Tripolis", "LI": "Vaduz", "LT": "Vilnius",
    "LU": "Luxemburg", "MG": "Antananarivo", "MW": "Lilongwe", "MY": "Kuala Lumpur", "MV": "Malé",
    "ML": "Bamako", "MT": "Valletta", "MA": "Rabat", "MH": "Majuro", "MR": "Nouakchott",
    "MU": "Port Louis", "MX": "Mexiko-Stadt", "FM": "Palikir", "MD": "Chișinău", "MC": "Monaco",
    "MN": "Ulaanbaatar", "ME": "Podgorica", "MZ": "Maputo", "MM": "Naypyidaw", "NA": "Windhoek",
    "NR": "Yaren", "NP": "Kathmandu", "NZ": "Wellington", "NI": "Managua", "NL": "Amsterdam",
    "NE": "Niamey", "NG": "Abuja", "KP": "Pjöngjang", "MK": "Skopje", "NO": "Oslo",
    "OM": "Maskat", "TL": "Dili", "PK": "Islamabad", "PW": "Ngerulmud", "PA": "Panama-Stadt",
    "PG": "Port Moresby", "PY": "Asunción", "PE": "Lima", "PH": "Manila", "PL": "Warschau",
    "PT": "Lissabon", "RW": "Kigali", "RO": "Bukarest", "RU": "Moskau", "SB": "Honiara",
    "ZM": "Lusaka", "WS": "Apia", "SM": "San Marino", "SA": "Riad", "SE": "Stockholm",
    "CH": "Bern", "SN": "Dakar", "RS": "Belgrad", "SC": "Victoria", "SL": "Freetown",
    "ZW": "Harare", "SG": "Singapur", "SK": "Bratislava", "SI": "Ljubljana", "SO": "Mogadischu",
    "ES": "Madrid", "LK": "Sri Jayawardenepura Kotte", "KN": "Basseterre", "LC": "Castries", "VC": "Kingstown",
    "SD": "Khartum", "SR": "Paramaribo", "SZ": "Mbabane", "SY": "Damaskus", "ST": "São Tomé",
    "ZA": "Pretoria", "KR": "Seoul", "SS": "Juba", "TJ": "Duschanbe", "TZ": "Dodoma",
    "TH": "Bangkok", "TG": "Lomé", "TO": "Nukuʻalofa", "TT": "Port of Spain", "TD": "N'Djamena",
    "CZ": "Prag", "TN": "Tunis", "TM": "Aschgabat", "TV": "Funafuti", "TR": "Ankara",
    "UG": "Kampala", "UA": "Kiew", "HU": "Budapest", "UY": "Montevideo", "UZ": "Taschkent",
    "VU": "Port Vila", "VE": "Caracas", "AE": "Abu Dhabi", "US": "Washington, D.C.", "GB": "London",
    "VN": "Hanoi", "BY": "Minsk", "CF": "Bangui", "CY": "Nikosia", "EG": "Kairo",
    "GQ": "Malabo", "ET": "Addis Abeba", "AT": "Wien", "GL": "Nuuk", "FO": "Tórshavn",
    "XK": "Pristina", "TW": "Taipeh", "PS": "Ramallah", "EH": "El Aaiún",
    "CK": "Avarua", "NU": "Alofi", "AB": "Suchumi", "OS": "Zchinwali",
    "NC": "Nord-Nikosia", "SLD": "Hargeisa"
]

let capitalPronunciationByCountryCode: [String: String] = [
    "AF": "Ka-bul", "DZ": "Al-dschir", "AO": "Lu-an-da", "AZ": "Ba-ku", "BH": "Ma-na-ma",
    "BD": "Dha-ka", "BZ": "Bel-mo-pan", "BJ": "Por-to No-vo", "BT": "Tim-pu",
    "BA": "Sa-ra-je-wo", "BW": "Ga-bo-ro-ne", "BR": "Bra-si-li-a", "BN": "Ban-dar Se-ri Be-ga-wan",
    "BF": "Wa-ga-du-gu", "BI": "Gi-te-ga", "CN": "Pe-king", "DJ": "Dschi-bu-ti",
    "CI": "Ja-mu-ssu-kro", "ER": "As-ma-ra", "FJ": "Su-wa", "GA": "Li-bre-wil",
    "GM": "Ban-dschul", "GE": "Tif-lis", "GH": "Ak-kra", "GN": "Ko-na-kri",
    "GW": "Bi-ssau", "HT": "Port-o-Prens", "IN": "Neu-De-li", "ID": "Dja-kar-ta",
    "IQ": "Bag-dad", "IR": "Te-he-ran", "IS": "Reik-ja-wik", "IL": "Je-ru-sa-lem",
    "JP": "To-kio", "YE": "Sa-na-a", "JO": "Am-man", "KH": "Pnom Pen",
    "CV": "Pra-ja", "KZ": "As-ta-na", "QA": "Do-ha", "KE": "Nai-ro-bi",
    "KG": "Bisch-kek", "KI": "Sauth Ta-ra-wa", "KM": "Mo-ro-ni", "CG": "Bra-sa-wil",
    "CD": "Kin-scha-sa", "KW": "Ku-wait-Stadt", "LA": "Wi-en-tian", "LS": "Ma-se-ru",
    "LB": "Bei-rut", "LR": "Mon-ro-wi-a", "LY": "Tri-po-lis", "MG": "An-ta-na-na-ri-wo",
    "MW": "Li-long-we", "MY": "Ku-a-la Lum-pur", "MV": "Ma-le", "ML": "Ba-ma-ko",
    "MA": "Ra-bat", "MH": "Ma-dschu-ro", "MR": "Nu-ak-schott", "MU": "Port Lu-is",
    "FM": "Pa-li-kir", "MD": "Ki-schi-nau", "MN": "U-lan-ba-tor", "MZ": "Ma-pu-to",
    "MM": "Ne-pi-do", "NA": "Wind-huk", "NR": "Ja-ren", "NP": "Kat-man-du",
    "NE": "Ni-a-me", "NG": "A-bu-dscha", "KP": "Pjöng-jang", "OM": "Mas-kat",
    "TL": "Di-li", "PK": "Is-la-ma-bad", "PW": "Nge-rul-mud", "PG": "Port Mors-bi",
    "PY": "A-sun-si-on", "PE": "Li-ma", "PH": "Ma-ni-la", "RW": "Ki-ga-li",
    "RU": "Mos-kau", "SB": "Ho-ni-a-ra", "ZM": "Lu-sa-ka", "WS": "A-pi-a",
    "SA": "Ri-ad", "SN": "Se-ne-gal", "SC": "Vik-to-ri-a", "SL": "Fri-taun",
    "ZW": "Ha-ra-re", "LK": "Sri Dschaja-war-de-ne-pu-ra Kot-te", "KN": "Bass-tehr",
    "LC": "Kas-tris", "VC": "Kings-taun", "SD": "Khar-tum", "SR": "Pa-ra-ma-ri-bo",
    "SZ": "Mba-ba-ne", "SY": "Da-mas-kus", "ST": "Sao To-me", "KR": "Se-ul",
    "SS": "Dschu-ba", "TJ": "Du-schan-be", "TZ": "Do-do-ma", "TH": "Bang-kok",
    "TG": "Lo-me", "TO": "Nu-ku-a-lo-fa", "TD": "Nd-scha-me-na", "TM": "Asch-ga-bat",
    "TV": "Fu-na-fu-ti", "UG": "Kam-pa-la", "UZ": "Taschkent", "VU": "Port Wi-la",
    "AE": "A-bu Da-bi", "VN": "Ha-noi", "CF": "Ban-gi", "EG": "Kai-ro",
    "GQ": "Ma-la-bo", "ET": "Ad-dis A-be-ba", "FO": "Tor-schhaun", "XK": "Pris-ti-na",
    "TW": "Tai-peh", "PS": "Ra-mal-lah", "EH": "El A-jun", "CK": "A-wa-ru-a",
    "NU": "A-lo-fi", "AB": "Su-chu-mi", "OS": "Zchin-wa-li", "NC": "Nord-Ni-ko-si-a",
    "SLD": "Har-gei-sa"
]

let allCountries: [Country] = [
    Country(code: "AF", name: "Afghanistan", continent: "Asien"),
    Country(code: "AL", name: "Albanien", continent: "Europa"),
    Country(code: "DZ", name: "Algerien", continent: "Afrika"),
    Country(code: "AD", name: "Andorra", continent: "Europa"),
    Country(code: "AO", name: "Angola", continent: "Afrika"),
    Country(code: "AG", name: "Antigua und Barbuda", continent: "Nordamerika"),
    Country(code: "AR", name: "Argentinien", continent: "Südamerika"),
    Country(code: "AM", name: "Armenien", continent: "Asien"),
    Country(code: "AZ", name: "Aserbaidschan", continent: "Europa"),
    Country(code: "AU", name: "Australien", continent: "Ozeanien"),
    Country(code: "BS", name: "Bahamas", continent: "Nordamerika"),
    Country(code: "BH", name: "Bahrain", continent: "Asien"),
    Country(code: "BD", name: "Bangladesch", continent: "Asien"),
    Country(code: "BB", name: "Barbados", continent: "Nordamerika"),
    Country(code: "BE", name: "Belgien", continent: "Europa"),
    Country(code: "BZ", name: "Belize", continent: "Nordamerika"),
    Country(code: "BJ", name: "Benin", continent: "Afrika"),
    Country(code: "BT", name: "Bhutan", continent: "Asien"),
    Country(code: "BO", name: "Bolivien", continent: "Südamerika"),
    Country(code: "BA", name: "Bosnien und Herzegowina", continent: "Europa"),
    Country(code: "BW", name: "Botswana", continent: "Afrika"),
    Country(code: "BR", name: "Brasilien", continent: "Südamerika"),
    Country(code: "BN", name: "Brunei", continent: "Asien"),
    Country(code: "BG", name: "Bulgarien", continent: "Europa"),
    Country(code: "BF", name: "Burkina Faso", continent: "Afrika"),
    Country(code: "BI", name: "Burundi", continent: "Afrika"),
    Country(code: "CL", name: "Chile", continent: "Südamerika"),
    Country(code: "CN", name: "China", continent: "Asien"),
    Country(code: "CR", name: "Costa Rica", continent: "Nordamerika"),
    Country(code: "DE", name: "Deutschland", continent: "Europa"),
    Country(code: "DM", name: "Dominica", continent: "Nordamerika"),
    Country(code: "DO", name: "Dominikanische Republik", continent: "Nordamerika"),
    Country(code: "DJ", name: "Dschibuti", continent: "Afrika"),
    Country(code: "DK", name: "Dänemark", continent: "Europa"),
    Country(code: "EC", name: "Ecuador", continent: "Südamerika"),
    Country(code: "SV", name: "El Salvador", continent: "Nordamerika"),
    Country(code: "CI", name: "Elfenbeinküste", continent: "Afrika"),
    Country(code: "ER", name: "Eritrea", continent: "Afrika"),
    Country(code: "EE", name: "Estland", continent: "Europa"),
    Country(code: "FJ", name: "Fidschi", continent: "Ozeanien"),
    Country(code: "FI", name: "Finnland", continent: "Europa"),
    Country(code: "FO", name: "Färöer", continent: "Europa"),
    Country(code: "FR", name: "Frankreich", continent: "Europa"),
    Country(code: "GA", name: "Gabun", continent: "Afrika"),
    Country(code: "GM", name: "Gambia", continent: "Afrika"),
    Country(code: "GE", name: "Georgien", continent: "Asien"),
    Country(code: "GH", name: "Ghana", continent: "Afrika"),
    Country(code: "GD", name: "Grenada", continent: "Nordamerika"),
    Country(code: "GR", name: "Griechenland", continent: "Europa"),
    Country(code: "GL", name: "Grönland", continent: "Nordamerika"),
    Country(code: "GT", name: "Guatemala", continent: "Nordamerika"),
    Country(code: "GN", name: "Guinea", continent: "Afrika"),
    Country(code: "GW", name: "Guinea-Bissau", continent: "Afrika"),
    Country(code: "GY", name: "Guyana", continent: "Südamerika"),
    Country(code: "HT", name: "Haiti", continent: "Nordamerika"),
    Country(code: "HN", name: "Honduras", continent: "Nordamerika"),
    Country(code: "IN", name: "Indien", continent: "Asien"),
    Country(code: "ID", name: "Indonesien", continent: "Asien"),
    Country(code: "IQ", name: "Irak", continent: "Asien"),
    Country(code: "IR", name: "Iran", continent: "Asien"),
    Country(code: "IE", name: "Irland", continent: "Europa"),
    Country(code: "IS", name: "Island", continent: "Europa"),
    Country(code: "IL", name: "Israel", continent: "Asien"),
    Country(code: "IT", name: "Italien", continent: "Europa"),
    Country(code: "JM", name: "Jamaika", continent: "Nordamerika"),
    Country(code: "JP", name: "Japan", continent: "Asien"),
    Country(code: "YE", name: "Jemen", continent: "Asien"),
    Country(code: "JO", name: "Jordanien", continent: "Asien"),
    Country(code: "KH", name: "Kambodscha", continent: "Asien"),
    Country(code: "CM", name: "Kamerun", continent: "Afrika"),
    Country(code: "CA", name: "Kanada", continent: "Nordamerika"),
    Country(code: "CV", name: "Kap Verde", continent: "Afrika"),
    Country(code: "KZ", name: "Kasachstan", continent: "Asien"),
    Country(code: "QA", name: "Katar", continent: "Asien"),
    Country(code: "KE", name: "Kenia", continent: "Afrika"),
    Country(code: "KG", name: "Kirgisistan", continent: "Asien"),
    Country(code: "KI", name: "Kiribati", continent: "Ozeanien"),
    Country(code: "CO", name: "Kolumbien", continent: "Südamerika"),
    Country(code: "KM", name: "Komoren", continent: "Afrika"),
    Country(code: "CG", name: "Kongo", continent: "Afrika"),
    Country(code: "CD", name: "Kongo (Dem. Rep.)", continent: "Afrika"),
    Country(code: "HR", name: "Kroatien", continent: "Europa"),
    Country(code: "CU", name: "Kuba", continent: "Nordamerika"),
    Country(code: "KW", name: "Kuwait", continent: "Asien"),
    Country(code: "LA", name: "Laos", continent: "Asien"),
    Country(code: "LS", name: "Lesotho", continent: "Afrika"),
    Country(code: "LV", name: "Lettland", continent: "Europa"),
    Country(code: "LB", name: "Libanon", continent: "Asien"),
    Country(code: "LR", name: "Liberia", continent: "Afrika"),
    Country(code: "LY", name: "Libyen", continent: "Afrika"),
    Country(code: "LI", name: "Liechtenstein", continent: "Europa"),
    Country(code: "LT", name: "Litauen", continent: "Europa"),
    Country(code: "LU", name: "Luxemburg", continent: "Europa"),
    Country(code: "MG", name: "Madagaskar", continent: "Afrika"),
    Country(code: "MW", name: "Malawi", continent: "Afrika"),
    Country(code: "MY", name: "Malaysia", continent: "Asien"),
    Country(code: "MV", name: "Malediven", continent: "Asien"),
    Country(code: "ML", name: "Mali", continent: "Afrika"),
    Country(code: "MT", name: "Malta", continent: "Europa"),
    Country(code: "MA", name: "Marokko", continent: "Afrika"),
    Country(code: "MH", name: "Marshallinseln", continent: "Ozeanien"),
    Country(code: "MR", name: "Mauretanien", continent: "Afrika"),
    Country(code: "MU", name: "Mauritius", continent: "Afrika"),
    Country(code: "MX", name: "Mexiko", continent: "Nordamerika"),
    Country(code: "FM", name: "Mikronesien", continent: "Ozeanien"),
    Country(code: "MD", name: "Moldawien", continent: "Europa"),
    Country(code: "MC", name: "Monaco", continent: "Europa"),
    Country(code: "MN", name: "Mongolei", continent: "Asien"),
    Country(code: "ME", name: "Montenegro", continent: "Europa"),
    Country(code: "MZ", name: "Mosambik", continent: "Afrika"),
    Country(code: "MM", name: "Myanmar", continent: "Asien"),
    Country(code: "NA", name: "Namibia", continent: "Afrika"),
    Country(code: "NR", name: "Nauru", continent: "Ozeanien"),
    Country(code: "NP", name: "Nepal", continent: "Asien"),
    Country(code: "NZ", name: "Neuseeland", continent: "Ozeanien"),
    Country(code: "NI", name: "Nicaragua", continent: "Nordamerika"),
    Country(code: "NL", name: "Niederlande", continent: "Europa"),
    Country(code: "NE", name: "Niger", continent: "Afrika"),
    Country(code: "NG", name: "Nigeria", continent: "Afrika"),
    Country(code: "KP", name: "Nordkorea", continent: "Asien"),
    Country(code: "MK", name: "Nordmazedonien", continent: "Europa"),
    Country(code: "NO", name: "Norwegen", continent: "Europa"),
    Country(code: "OM", name: "Oman", continent: "Asien"),
    Country(code: "TL", name: "Osttimor", continent: "Ozeanien"),
    Country(code: "PK", name: "Pakistan", continent: "Asien"),
    Country(code: "PW", name: "Palau", continent: "Ozeanien"),
    Country(code: "PA", name: "Panama", continent: "Nordamerika"),
    Country(code: "PG", name: "Papua-Neuguinea", continent: "Ozeanien"),
    Country(code: "PY", name: "Paraguay", continent: "Südamerika"),
    Country(code: "PE", name: "Peru", continent: "Südamerika"),
    Country(code: "PH", name: "Philippinen", continent: "Asien"),
    Country(code: "PL", name: "Polen", continent: "Europa"),
    Country(code: "PT", name: "Portugal", continent: "Europa"),
    Country(code: "RW", name: "Ruanda", continent: "Afrika"),
    Country(code: "RO", name: "Rumänien", continent: "Europa"),
    Country(code: "RU", name: "Russland", continent: "Europa"),
    Country(code: "SB", name: "Salomonen", continent: "Ozeanien"),
    Country(code: "ZM", name: "Sambia", continent: "Afrika"),
    Country(code: "WS", name: "Samoa", continent: "Ozeanien"),
    Country(code: "SM", name: "San Marino", continent: "Europa"),
    Country(code: "SA", name: "Saudi-Arabien", continent: "Asien"),
    Country(code: "SE", name: "Schweden", continent: "Europa"),
    Country(code: "CH", name: "Schweiz", continent: "Europa"),
    Country(code: "SN", name: "Senegal", continent: "Afrika"),
    Country(code: "RS", name: "Serbien", continent: "Europa"),
    Country(code: "SC", name: "Seychellen", continent: "Afrika"),
    Country(code: "SL", name: "Sierra Leone", continent: "Afrika"),
    Country(code: "ZW", name: "Simbabwe", continent: "Afrika"),
    Country(code: "SG", name: "Singapur", continent: "Asien"),
    Country(code: "SK", name: "Slowakei", continent: "Europa"),
    Country(code: "SI", name: "Slowenien", continent: "Europa"),
    Country(code: "SO", name: "Somalia", continent: "Afrika"),
    Country(code: "ES", name: "Spanien", continent: "Europa"),
    Country(code: "LK", name: "Sri Lanka", continent: "Asien"),
    Country(code: "KN", name: "St. Kitts und Nevis", continent: "Nordamerika"),
    Country(code: "LC", name: "St. Lucia", continent: "Nordamerika"),
    Country(code: "VC", name: "St. Vincent und die Grenadinen", continent: "Nordamerika"),
    Country(code: "SD", name: "Sudan", continent: "Afrika"),
    Country(code: "SR", name: "Suriname", continent: "Südamerika"),
    Country(code: "SZ", name: "Eswatini (Swasiland)", continent: "Afrika"),
    Country(code: "SY", name: "Syrien", continent: "Asien"),
    Country(code: "ST", name: "São Tomé und Príncipe", continent: "Afrika"),
    Country(code: "ZA", name: "Südafrika", continent: "Afrika"),
    Country(code: "KR", name: "Südkorea", continent: "Asien"),
    Country(code: "SS", name: "Südsudan", continent: "Afrika"),
    Country(code: "TJ", name: "Tadschikistan", continent: "Asien"),
    Country(code: "TZ", name: "Tansania", continent: "Afrika"),
    Country(code: "TH", name: "Thailand", continent: "Asien"),
    Country(code: "TG", name: "Togo", continent: "Afrika"),
    Country(code: "TO", name: "Tonga", continent: "Ozeanien"),
    Country(code: "TT", name: "Trinidad und Tobago", continent: "Nordamerika"),
    Country(code: "TD", name: "Tschad", continent: "Afrika"),
    Country(code: "CZ", name: "Tschechien", continent: "Europa"),
    Country(code: "TN", name: "Tunesien", continent: "Afrika"),
    Country(code: "TM", name: "Turkmenistan", continent: "Asien"),
    Country(code: "TV", name: "Tuvalu", continent: "Ozeanien"),
    Country(code: "TR", name: "Türkei", continent: "Europa"),
    Country(code: "UG", name: "Uganda", continent: "Afrika"),
    Country(code: "UA", name: "Ukraine", continent: "Europa"),
    Country(code: "HU", name: "Ungarn", continent: "Europa"),
    Country(code: "UY", name: "Uruguay", continent: "Südamerika"),
    Country(code: "UZ", name: "Usbekistan", continent: "Asien"),
    Country(code: "VU", name: "Vanuatu", continent: "Ozeanien"),
    Country(code: "VE", name: "Venezuela", continent: "Südamerika"),
    Country(code: "AE", name: "Vereinigte Arabische Emirate", continent: "Asien"),
    Country(code: "US", name: "Vereinigte Staaten", continent: "Nordamerika"),
    Country(code: "GB", name: "Vereinigtes Königreich", continent: "Europa"),
    Country(code: "VN", name: "Vietnam", continent: "Asien"),
    Country(code: "BY", name: "Belarus (Weißrussland)", continent: "Europa"),
    Country(code: "CF", name: "Zentralafrikanische Republik", continent: "Afrika"),
    Country(code: "CY", name: "Zypern", continent: "Europa"),
    Country(code: "EG", name: "Ägypten", continent: "Afrika"),
    Country(code: "GQ", name: "Äquatorialguinea", continent: "Afrika"),
    Country(code: "ET", name: "Äthiopien", continent: "Afrika"),
    Country(code: "AT", name: "Österreich", continent: "Europa")
]

let partiallyRecognizedCategory = "Teilweise anerkannt"

let worldCupWinnerCountryCodes: Set<String> = ["AR", "BR", "DE", "ES", "FR", "GB", "IT", "UY"]

let partiallyRecognizedCountries: [Country] = [
    Country(code: "XK", name: "Kosovo", continent: "Europa"),
    Country(code: "TW", name: "Taiwan", continent: "Asien"),
    Country(code: "PS", name: "Palästina", continent: "Asien"),
    Country(code: "EH", name: "Westsahara", continent: "Afrika"),
    Country(code: "CK", name: "Cookinseln", continent: "Ozeanien"),
    Country(code: "NU", name: "Niue", continent: "Ozeanien"),
    Country(code: "AB", name: "Abchasien", continent: "Asien"),
    Country(code: "OS", name: "Südossetien", continent: "Asien"),
    Country(code: "NC", name: "Nordzypern", continent: "Asien"),
    Country(code: "SLD", name: "Somaliland", continent: "Afrika")
]

let allPracticeCountries = allCountries + partiallyRecognizedCountries

let countryEnglishNameByCode: [String: String] = [
    "AF": "Afghanistan", "AL": "Albania", "DZ": "Algeria", "AD": "Andorra", "AO": "Angola",
    "AG": "Antigua and Barbuda", "AR": "Argentina", "AM": "Armenia", "AZ": "Azerbaijan", "AU": "Australia",
    "BS": "Bahamas", "BH": "Bahrain", "BD": "Bangladesh", "BB": "Barbados", "BE": "Belgium",
    "BZ": "Belize", "BJ": "Benin", "BT": "Bhutan", "BO": "Bolivia", "BA": "Bosnia and Herzegovina",
    "BW": "Botswana", "BR": "Brazil", "BN": "Brunei", "BG": "Bulgaria", "BF": "Burkina Faso",
    "BI": "Burundi", "CL": "Chile", "CN": "China", "CR": "Costa Rica", "DE": "Germany",
    "DM": "Dominica", "DO": "Dominican Republic", "DJ": "Djibouti", "DK": "Denmark", "EC": "Ecuador",
    "SV": "El Salvador", "CI": "Cote d'Ivoire", "ER": "Eritrea", "EE": "Estonia", "FJ": "Fiji",
    "FI": "Finland", "FO": "Faroe Islands", "FR": "France", "GA": "Gabon", "GM": "Gambia", "GE": "Georgia",
    "GH": "Ghana", "GD": "Grenada", "GR": "Greece", "GL": "Greenland", "GT": "Guatemala", "GN": "Guinea",
    "GW": "Guinea-Bissau", "GY": "Guyana", "HT": "Haiti", "HN": "Honduras", "IN": "India",
    "ID": "Indonesia", "IQ": "Iraq", "IR": "Iran", "IE": "Ireland", "IS": "Iceland",
    "IL": "Israel", "IT": "Italy", "JM": "Jamaica", "JP": "Japan", "YE": "Yemen",
    "JO": "Jordan", "KH": "Cambodia", "CM": "Cameroon", "CA": "Canada", "CV": "Cape Verde",
    "KZ": "Kazakhstan", "QA": "Qatar", "KE": "Kenya", "KG": "Kyrgyzstan", "KI": "Kiribati",
    "CO": "Colombia", "KM": "Comoros", "CG": "Congo", "CD": "Democratic Republic of the Congo", "HR": "Croatia",
    "CU": "Cuba", "KW": "Kuwait", "LA": "Laos", "LS": "Lesotho", "LV": "Latvia",
    "LB": "Lebanon", "LR": "Liberia", "LY": "Libya", "LI": "Liechtenstein", "LT": "Lithuania",
    "LU": "Luxembourg", "MG": "Madagascar", "MW": "Malawi", "MY": "Malaysia", "MV": "Maldives",
    "ML": "Mali", "MT": "Malta", "MA": "Morocco", "MH": "Marshall Islands", "MR": "Mauritania",
    "MU": "Mauritius", "MX": "Mexico", "FM": "Micronesia", "MD": "Moldova", "MC": "Monaco",
    "MN": "Mongolia", "ME": "Montenegro", "MZ": "Mozambique", "MM": "Myanmar", "NA": "Namibia",
    "NR": "Nauru", "NP": "Nepal", "NZ": "New Zealand", "NI": "Nicaragua", "NL": "Netherlands",
    "NE": "Niger", "NG": "Nigeria", "KP": "North Korea", "MK": "North Macedonia", "NO": "Norway",
    "OM": "Oman", "TL": "East Timor", "PK": "Pakistan", "PW": "Palau", "PA": "Panama",
    "PG": "Papua New Guinea", "PY": "Paraguay", "PE": "Peru", "PH": "Philippines", "PL": "Poland",
    "PT": "Portugal", "RW": "Rwanda", "RO": "Romania", "RU": "Russia", "SB": "Solomon Islands",
    "ZM": "Zambia", "WS": "Samoa", "SM": "San Marino", "SA": "Saudi Arabia", "SE": "Sweden",
    "CH": "Switzerland", "SN": "Senegal", "RS": "Serbia", "SC": "Seychelles", "SL": "Sierra Leone",
    "ZW": "Zimbabwe", "SG": "Singapore", "SK": "Slovakia", "SI": "Slovenia", "SO": "Somalia",
    "ES": "Spain", "LK": "Sri Lanka", "KN": "St. Kitts and Nevis", "LC": "St. Lucia", "VC": "St. Vincent and the Grenadines",
    "SD": "Sudan", "SR": "Suriname", "SZ": "Eswatini", "SY": "Syria", "ST": "Sao Tome and Principe",
    "ZA": "South Africa", "KR": "South Korea", "SS": "South Sudan", "TJ": "Tajikistan", "TZ": "Tanzania",
    "TH": "Thailand", "TG": "Togo", "TO": "Tonga", "TT": "Trinidad and Tobago", "TD": "Chad",
    "CZ": "Czechia", "TN": "Tunisia", "TM": "Turkmenistan", "TV": "Tuvalu", "TR": "Turkey",
    "UG": "Uganda", "UA": "Ukraine", "HU": "Hungary", "UY": "Uruguay", "UZ": "Uzbekistan",
    "VU": "Vanuatu", "VE": "Venezuela", "AE": "United Arab Emirates", "US": "United States", "GB": "United Kingdom",
    "VN": "Vietnam", "BY": "Belarus", "CF": "Central African Republic", "CY": "Cyprus", "EG": "Egypt",
    "GQ": "Equatorial Guinea", "ET": "Ethiopia", "AT": "Austria", "XK": "Kosovo", "TW": "Taiwan",
    "PS": "Palestine", "EH": "Western Sahara", "CK": "Cook Islands", "NU": "Niue",
    "AB": "Abkhazia", "OS": "South Ossetia", "NC": "Northern Cyprus", "SLD": "Somaliland"
]
