import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const workerUrl = new URL('../cloud/meta-scheduler/src/index.ts', import.meta.url)
const schemaUrl = new URL('../cloud/meta-scheduler/schema.sql', import.meta.url)

test('staging lane has dedicated routes, claims and no publishing call', async () => {
  const source = await readFile(workerUrl, 'utf8')
  for (const route of ['/staging/runs', '/staging/claims', '/staging/receipts', '/staging/poll', '/staging/feed']) {
    assert.match(source, new RegExp(route.replaceAll('/', '\\/')))
  }
  const start = source.indexOf('const stageInstagramContainer')
  const end = source.indexOf('const processJob', start)
  assert.ok(start >= 0 && end > start)
  const stagingLane = source.slice(start, end)
  assert.doesNotMatch(stagingLane, /media_publish/)
  assert.doesNotMatch(stagingLane, /video_state:\s*"PUBLISHED"/)
  assert.doesNotMatch(stagingLane, /meta_publication_jobs/)
  assert.match(stagingLane, /video_state:\s*"DRAFT"/)
  assert.match(stagingLane, /fields:\s*"published,status"/)
})

test('staging schema is separate and cannot authorize publication', async () => {
  const schema = await readFile(schemaUrl, 'utf8')
  assert.match(schema, /CREATE TABLE IF NOT EXISTS upload_staging_runs/)
  assert.match(schema, /publication_authorized INTEGER NOT NULL DEFAULT 0 CHECK \(publication_authorized = 0\)/)
  assert.match(schema, /idempotency_key TEXT NOT NULL UNIQUE/)
  assert.match(schema, /initial_visibility_state TEXT NOT NULL CHECK \(initial_visibility_state IN \('not_created', 'unknown'\)\)/)

  const source = await readFile(workerUrl, 'utf8')
  const start = source.indexOf('const ensureStagingSchema =')
  const end = source.indexOf('const stagingEvent =', start)
  const runtimeSchema = source.slice(start, end)
  assert.match(runtimeSchema, /publication_authorized INTEGER NOT NULL DEFAULT 0 CHECK \(publication_authorized = 0\)/)
  assert.match(runtimeSchema, /FOREIGN KEY\(run_id\) REFERENCES upload_staging_runs\(run_id\)/)
})

test('public staging feed omits remote IDs and private metadata', async () => {
  const source = await readFile(workerUrl, 'utf8')
  const start = source.indexOf('const stagingFeed =')
  const end = source.indexOf('const publicationFailureCode =', start)
  assert.ok(start >= 0 && end > start)
  const feed = source.slice(start, end)
  assert.doesNotMatch(feed, /remoteObjectId|remote_object_id|metadata_json|last_error|accountFingerprint/)
  assert.match(feed, /publicationAuthorized:\s*false/)
  assert.match(feed, /publishedAt:\s*null/)
  assert.match(feed, /publicUrl:\s*null/)
})

test('public production feed exposes only safe queue state and categorized failures', async () => {
  const source = await readFile(workerUrl, 'utf8')
  assert.match(source, /url\.pathname === "\/publication\/feed"/)
  const start = source.indexOf('const publicationFeed =')
  const end = source.indexOf('const analyticsMetricNames', start)
  assert.ok(start >= 0 && end > start)
  const feed = source.slice(start, end)
  assert.match(feed, /lane:\s*"production-publication"/)
  assert.match(feed, /failureCode:/)
  assert.match(feed, /contentId:/)
  assert.match(feed, /scheduledAt:/)
  assert.doesNotMatch(feed, /metadata_json|media_url|media_project|media_branch|container_id|platform_video_id|publication_url/)
  assert.doesNotMatch(feed, /lastError\s*:/)
  assert.doesNotMatch(feed, /jobId\s*:/)
})

test('Meta credentials keep Facebook and Instagram token types separate and fail closed', async () => {
  const source = await readFile(workerUrl, 'utf8')
  const credentialsStart = source.indexOf('const instagramTokenFor =')
  const credentialsEnd = source.indexOf('const graph =', credentialsStart)
  assert.ok(credentialsStart >= 0 && credentialsEnd > credentialsStart)
  const credentials = source.slice(credentialsStart, credentialsEnd)
  assert.match(credentials, /META_INSTAGRAM_USER_ACCESS_TOKEN/)
  assert.match(credentials, /env\.META_FACEBOOK_PAGE_ACCESS_TOKEN\?\.trim\(\)/)
  assert.doesNotMatch(credentials, /pageTokenFor|fields:\s*"access_token"/)
  assert.match(credentials, /code === 190/)
  assert.match(credentials, /code >= 200 && code <= 299/)

  const queueStart = source.indexOf('const processJob =')
  const queueEnd = source.indexOf('const stagingAuthError =', queueStart)
  const queue = source.slice(queueStart, queueEnd)
  assert.match(queue, /error instanceof MetaApiError/)
  assert.match(queue, /metaCredentialStatus\(payload\.platform, env\)/)

  const readyStart = source.indexOf('if (request.method === "GET" && url.pathname === "/ready")')
  const readyEnd = source.indexOf('if (request.method === "POST" && url.pathname === "/analytics\/refresh-meta")', readyStart)
  const ready = source.slice(readyStart, readyEnd)
  assert.match(ready, /credentials_invalid/)
  assert.match(ready, /metaCredentialStatus\("instagram", env\)/)
  assert.match(ready, /metaCredentialStatus\("facebook", env\)/)
})

test('successful state transitions can explicitly clear an earlier provider error', async () => {
  const source = await readFile(workerUrl, 'utf8')
  const start = source.indexOf('const setState =')
  const end = source.indexOf('const facebookReelUrl =', start)
  const setState = source.slice(start, end)
  assert.match(setState, /Object\.prototype\.hasOwnProperty\.call\(changes, key\)/)
  assert.doesNotMatch(setState, /changes\.last_error \?\? job\.last_error/)
})

test('protected staging receipts expose an authoritative confirmation timestamp', async () => {
  const source = await readFile(workerUrl, 'utf8')
  const start = source.indexOf('const stagingTargetResponse =')
  const end = source.indexOf('const stagingRunResponse =', start)
  assert.ok(start >= 0 && end > start)
  const response = source.slice(start, end)
  assert.match(response, /confirmedAt:/)
  assert.match(response, /target\.updated_at/)
})

test('temporary Pages media cleanup removes active preview aliases explicitly', async () => {
  const source = await readFile(workerUrl, 'utf8')
  assert.equal((source.match(/deployments\/\$\{deployment\.id\}\?force=true/g) ?? []).length, 2)
  const cleanupStart = source.indexOf('interface PagesDeployment')
  const cleanupEnd = source.indexOf('const stageInstagramContainer', cleanupStart)
  const cleanup = source.slice(cleanupStart, cleanupEnd)
  assert.match(cleanup, /searchParams\.set\("page"/)
  assert.match(cleanup, /searchParams\.set\("per_page", "100"\)/)
  assert.match(cleanup, /pagesOrigin\(deployment\.url\) === expectedOrigin/)
  assert.match(cleanup, /\["container_unpublished", "expired"\]/)
  assert.match(cleanup, /facebook\.workflow_state === "draft"/)
  assert.doesNotMatch(cleanup, /\["draft", "failed", "reconcile_required"/)
  const start = source.indexOf('const pollStagingRun =')
  const end = source.indexOf('interface StagingFeedTargetRow', start)
  const poll = source.slice(start, end)
  assert.match(poll, /inspectInstagramStaging\(env, runId, false\)/)
  assert.match(poll, /cleanupStagingMediaIfSafe\(env, runId\)/)
})

test('Facebook publications and analytics use stable Reel links and expose partial insight state safely', async () => {
  const source = await readFile(workerUrl, 'utf8')
  assert.match(source, /https:\/\/www\.facebook\.com\/reel\/\$\{encodeURIComponent\(id\)\}/)
  assert.match(source, /verifiedFacebookPermalink\(item\.id, item\.permalink_url\)/)
  const collectorStart = source.indexOf('const collectFacebookAnalytics =')
  const collectorEnd = source.indexOf('const refreshMetaAnalyticsIfDue =', collectorStart)
  assert.ok(collectorStart >= 0 && collectorEnd > collectorStart)
  const collector = source.slice(collectorStart, collectorEnd)
  assert.match(collector, /status: failureCount > 0 \? "partial" : "available"/)
  assert.match(collector, /Video-Insights fehlen fuer/)
  assert.doesNotMatch(collector, /JSON\.stringify\(.*error/)
  assert.match(source, /"blue_reels_play_count"/)
  assert.match(source, /"post_impressions_unique"/)
  assert.match(source, /"post_video_avg_time_watched"/)
  assert.match(source, /"post_video_view_time"/)
  assert.match(source, /hasNumericInsight\(insights, facebookReelMetrics\)/)
  assert.match(source, /hasNumericInsight\(insights, facebookClassicVideoMetrics\)/)
})
